homeapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$', views.book, name='book'),

]

homework/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^homeapp/', include('homeapp.urls')),

]

homeapp/models.py
from django.db import models
from multiselectfield import MultiSelectField

# Create your models here.


class Cities(models.Model):
    city_name = models.CharField(max_length=200)

    def __str__(self):
        return self.city_name


class Cleaner(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    quality_score = models.FloatField(5)
    cities = models.ManyToManyField(Cities, MultiSelectField(Cities), null=True)

    def __str__(self):
        return str(self.first_name) + " " + str(self .last_name)


class Customer(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=200)

    def __str__(self):
        return str(self.first_name) + " " + str(self.last_name)


class Booking(models.Model):
    customer = models.ForeignKey(Customer)
    cleaner = models.ForeignKey(Cleaner)
    city_id = models.IntegerField(null=False)
    book_date = models.DateTimeField()

    def __str__(self):
        return str(self.customer.first_name) + " " + str(self.customer.last_name)

homeapp/forms.py
from django import forms

from .models import *


class CustumerForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=True)

    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=True)

    phone_number = forms.CharField(label='Phone Number', widget=forms.TextInput(attrs={'type':
                                                                                           'number'}), required=True)

    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'phone_number']


class BookingForm(forms.ModelForm):
    first_name = forms.CharField(label='Customer Name', widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=True)

    last_name = forms.CharField(label='Customer Name', widget=forms.TextInput(attrs={'class': 'form-control'}),
                                required=True)

    phone_number = forms.CharField(label='Phone Number', widget=forms.TextInput(attrs={'type': 'number'}),
                                   required=True)

    date = forms.DateTimeField()

    CITIES_CHOICES = set()
    city_obj = Cities.objects.all()
    for city in city_obj:
        CITIES_CHOICES.add((city.id, city.city_name))
    city = forms.MultipleChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
                                     choices=CITIES_CHOICES, label="Select City")

    class Meta:
        model = Booking
        fields = ['first_name', 'last_name', 'city', 'phone_number', 'date']

homeapp/views.py
from django.shortcuts import render, redirect

from random import choice
from .models import *
from homeapp.forms import CustumerForm, BookingForm
import datetime

# Create your views here.


def index(request):
    if request.method == 'POST':
        if 'save' in request.POST:

            customer_no = request.POST.get('phone_number')
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')

            # set Customer
            customer_chk = Customer.objects.filter(phone_number=customer_no).exists()
            if customer_chk == False:
                customer_obj = Customer(first_name=first_name, last_name=first_name, phone_number=customer_no)
                customer_obj.save()
                message = 'Signup successfully.'
                form = BookingForm({'first_name': first_name, 'last_name': last_name, 'phone_number': customer_no})
            else:
                message = 'User alrady registered.'

                form = BookingForm({'first_name': first_name, 'last_name': last_name,
                                    'phone_number': customer_no})

            context = {'form': form, 'type': 'booking', 'message': message}
            return render(request, 'homeapp/index.html', context)

        if 'book' in request.POST:
            context = book(request)

            return render(request, 'homeapp/index.html', context)

    else:
        form = CustumerForm()
        context = {'form': form, 'type': 'signup'}

        return render(request, 'homeapp/index.html', context)


def book(request):
    customer_no = request.POST.get('phone_number')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    city = request.POST.get('city')
    get_date = request.POST.get('date')
    date = datetime.datetime.strptime(get_date, "%d-%m-%Y")

    customer_full_name = first_name + " " + last_name

    customer_obj = Customer.objects.get(phone_number=customer_no)
    city_obj = Cities.objects.get(id=city)
    cleaner_obj = Cleaner.objects.filter(cities=city_obj)

    book_summry = dict()
    cleaner_list = list()
    for cleaner in cleaner_obj:
        cleaner_chk = Booking.objects.filter(cleaner=cleaner).exists()
        if cleaner_chk == False:
            cleaner_list.append(cleaner)

    if len(cleaner_list) >= 1:
        cleaner_assign = choice(cleaner_list)
        book_obj = Booking(customer=customer_obj, cleaner=cleaner_assign, book_date=date, city_id=city)
        book_obj.save()

        # add bookoing detail in dictionary.
        book_summry['Customer Name'] = customer_full_name
        book_summry['City'] = city_obj.city_name
        book_summry['Booking Date'] = date
        book_summry['Cleaner'] = cleaner_assign.first_name + " " + cleaner_assign.last_name

        message = 'Book successfully!'
        context = {'type': 'booked', 'message': message, 'book_summry': book_summry}

        return context

    else:
        message = 'We could not fulfill your request at this time.'
        form = BookingForm({'first_name': first_name, 'last_name': last_name, 'phone_umber': customer_no})
        context = {'form': form, 'type': 'booking', 'message': message}

        return context

homeapp/templates/homeapp/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Work</title>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
    {#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>#}

</head>
<body>
<div class="container">
    <h1>Homework Application</h1><br>

    {% if type == 'signup' %}
    <h2>SignUp Form</h2><br>
    <form action="{% url 'index' %}" method="post">
        {% csrf_token %}
        {{ form}}
        <input type="submit" class="btn btn-primary" name="save" value="Sign Up">
    </form>
    {% endif %}
    {% if type == 'booking' %}
    <form action="{% url 'book' %}" method="post">
        {% csrf_token %}
        <h2>{{message}}</h2><br>
        <h2>Booking Form</h2><br>

        {{ form}}
        <br><br>
        <input type="submit" class="btn btn-primary" name="book" value="Book">
    </form>
    {% endif %}
    {% if type == 'booked' %}
    <h2>Booking Details</h2><br>
    {% if book_summry %}
    <table>
        {% for key, value in book_summry.items %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    {% endif %}

</div>
</body>
<script>
    $( '#id_date' ).datepicker({
        dateFormat: 'dd-mm-yy'
    });


</script>
</html>